### PR TITLE
- fix of #152 - get includes of cymunk without importing it

### PR DESCRIPTION
**Pull request by mahomahomaho**
It fixes issue #152, by not importing cymunk in setup.py

### CODE REVIEW

**Comment by mahomahomaho** [comment]
@Kovak Hi, if you accept this issue please merge it, because it blocks writing script to build kivent launcher for 2.2-dev branch

**Comment by Kovak** [comment]
:+1: 

Do you think that this approach should be taken for other places where we use the same pattern as this get_includes for cymunk?

**Comment by mahomahomaho** [comment]
It depends. It's not ideal solution, but best for modules, which import cythonized parts, like cython. But unlike kivy, which you can import without importing cythonized part. 

So in other words, if you can import pure python part of package to get get_includes, then it should stay as is. If it cannot, then I think it's better to use this trick.

**Comment by Kovak** [comment]
ahh I see so the better fix in the future would be that cymunk allows import of module without triggering import of compiled code immediately

**Comment by mahomahomaho** [comment]
On 08.08.2016 18:03, Kovak wrote:
> ahh I see so the better fix in the future would be that cymunk allows
> import of module without triggering import of compiled code immediately

Yes, it would be definitivly better. But I didn't know how to do it
without break compatibility with existing cymunk code, so I skipped that
way.

**Comment by Kovak** [comment]
Yes cymunk has a very difficult package structure at the moment. This is definitely the best option with existing cymunk

**Pull request merged**
