### PR TITLE
Update/kivent revival: Take 2!

### PR DESCRIPTION
**Pull request by tim-win**
Major Changes required to get KivEnt back up and running:

## on_kv_post
KivEnt examples almost all follow this pattern:

```
class TestGame(Widget):
    def __init__(self, **kwargs):
        super(TestGame, self).__init__(**kwargs)
        self.gameworld.init_gameworld(['system_ids'], callback=self.init_game)
        ...
```
 Combined with a .kv file that defines a gameworld:

```
TestGame:

<TestGame>:
	gameworld: gameworld
    GameWorld:
        id: gameworld
        ...
```

However, new functionality in Kivy includes moving kv rule application to a callback to give developers more control. You can see the implementation [here](https://github.com/kivy/kivy/pull/6257/files).

This is a breaking change, which is why I recommend bumping KivEnt to version 3.0- as far as I can tell everything will need to be updated to support this new pattern. However, after adding the `on_kv_post` method to cwidget, the fix is very straightforward for user code: just move the init gameworld call and you're on your way:

image

All but the `0_empty_kivy_app` examples were affected by this and have since been fixed.

## Relative Imports
Implicit relative imports have been removed in Kivy to support newer versions of python, and KivEnt is awash with them. As an example fix:

image

This PR cleans up relative imports throughout KivEnt. Addresses https://github.com/kivy/kivent/issues/265 and https://github.com/kivy/kivent/issues/209

## Print > Logger, when Possible
Compilation was broken on python 3+ due to at least two uses of print statements in KivEnt, but several locations were cleaned up to just use the kivy Logger instead of print.

## Fix the Pull Request Tests
PR tests were fixed. Travis and Appveyor both have approved this pull request.

Travis tests were moved from trusty to xenial, and the python versions were changed to 3.5, 3.6, and 3.7.

Appveyor was changed to the same python layout, and the target Kivy version upstream was pinned to 2.0.0.dev0 (rather than 1.10.1.dev0, which no longer exists in appveyor).

Also, cymunk is not correctly compiling in Windows/Python3.5+ environments. This is documented pretty well [here ](https://github.com/kivy/cymunk/issues/52) and also discussed [here](https://github.com/kivy/kivent/pull/218). As I'm not familiar with Windows build systems, I don't have a good test environment to try to fix this, this is a long standing issue, and I have to wash my hair tonight- I decided to dodge this issue.

The KivEnt/modules/cymunk install is conditionalized out.

## Other Small changes
Then a bunch of little things.

* Bumped the major version for all modules, with KivEnt going to 3.0
** This change meets semver.org's recommendation for new major versions, as it is backwards incompatible with old KivEnt builds due to the on_post_kv issue
* Fixed the exit code in the `scripts/install_all.sh` file, which is handy as heck.
* Cast a few doubles and a long to ints.
** I couldn't determine when this change occurred, but several calls to `len` were returning doubles, and then being saved to integer vars in kivy or elsewhere. This choked the cythonization so I went and fixed it.
* calls to dec_disabled were failing, because cwidget didn't implement it! Ported over the `*_disabled` methods from Kivy to cwidget. Addresses https://github.com/kivy/kivent/issues/276
* updated requirements.txt to poist to latest versions of Kivy and stuff.git
* Updated the `15_rotate_camera` example pretty thoroughly, because I couldn't figure out if it was rotating the camera in its original form. Once I could prove the camera rotation worked, it was only a little bit of cleanup to get the example to its current form.
* Had to remove a redeclaration of _proxy_ref. Addresses https://github.com/kivy/kivent/issues/277

To-Do before this can be merged:
* Get reviewed!

### CODE REVIEW

**Comment by tim-win** [comment]
Travis is up and running- Windows is next on the docket.

**Comment by tim-win** [comment]
Cymunk looks like it has been broken in windows based python 3.5+ environments for a while:

https://github.com/kivy/cymunk/issues/52

I'm not a Windows guy so I don't have great knowledge of how to just go fix it, nor do I have great test environments to make up meaningful workarounds. So I did what any good engineer does and kick the can down the road.

i.e. I conditionalized out the cymunk install.

Yes, this is a cop out, but this will allow us to testing building four of the five KivEnt modules in windows/python3.5, which is not nothing.

**Comment by jwasys** [comment]
Hello tim-win,

Thanks for the work, I'd love to try this out.

What would be a working combination of cymunk and kivent ? I cannot get anything to work here.

I have kivy-kivent-4709f07 and kivy 1.11.1

Thanks,

Arian

**Comment by tim-win** [comment]
Hey jwasys!

You'll need cymunk straight from the GitHub.com/kivy/cymunk repo, and I build latest master for github.com/kivy/kivy as well. You need to build extensions for kivy in place for the kivent build to find the ,cyx files, and will also need to add the kivy and cymunk builds to your pythonpath.

Writing all of that out on a phone, maybe I should update the readme with install instructions!

**Comment by tim-win** [comment]
Also, 4709f07 is incompatible with kivy 1.11, you'll need to use this branch to get it running!

**Comment by tim-win** [comment]
@Kovak Can you take a look at this PR? I think it's ready for review and merge.

@tito and @matham, you have closed the last 4 PRs to kivy/kivy and seem to be active maintainers in the org. Would you also be willing to take a look? I think KivEnt is just too cool to let bit rot like this :D

**Comment by jwasys** [comment]
Hello tim-win

Instructions would be great since I've been swimming for too long now...

Thanks

Arian

**Comment by tim-win** [comment]
Yes! A positive review!

I don't have access to merge to this repo / branch, as master is protected here, but please let me know if there's anything I can do to help.

**Comment by tim-win** [comment]
Arian- Happy to update the readmes next. I think there's a fair amount of house cleaning that can be done here, but I'd like to call this PR complete for now as it does get PR tests back into shape.

**Comment by yobagram** [comment]
> Travis is up and running- Windows is next on the docket.

I **was able** to build under **Windows**. Check core(2_basic_app) and cymunk(6_controlling_the_viewing_area).

**Pull request merged**
