### PR TITLE
Hexagonal, isometric and staggered maps support for maps module

### PR DESCRIPTION
**Pull request by udiboy1209**
Heres screenshots of them rendered in kivent:

hexagonal
isometric
staggered

@Kovak could you review these. To display them, you just have to change the [name here](https://github.com/udiboy1209/kivent/blob/f08388cbb1052c7baf0c92a6a860f680550cda5c/examples/14_tmx_loader/main.py#L48) to one of 'hexagonal', 'isometric', 'isometric_staggered'.

### CODE REVIEW

**Comment by spinningD20** [comment]
This is really exciting, nice work!

**Comment by udiboy1209** [comment]
They require python-tmx version 1.7 now for the hexagonal maps, so make sure you update before testing.

**Comment by spinningD20** [comment]
I tried to run the example after compiling and installing the modules, and I get this:

```
/usr/bin/python2.7 /storage/Downloads/kivent-f08388cbb1052c7baf0c92a6a860f680550cda5c/examples/14_tmx_loader/main.py
[INFO              ] [Kivy        ] v1.9.2-dev0
[INFO              ] [Python      ] v2.7.11 (default, Mar 31 2016, 06:18:34) 
[GCC 5.3.0]
[INFO              ] [Factory     ] 182 symbols loaded
[INFO              ] [Image       ] Providers: img_tex, img_dds, img_gif, img_sdl2, img_pil (img_ffpyplayer ignored)
[INFO              ] [OSC         ] using <multiprocessing> for socket
[INFO              ] [Window      ] Provider: sdl2(['window_egl_rpi'] ignored)
[INFO              ] [GL          ] OpenGL version <4.5.0 NVIDIA 367.27>
[INFO              ] [GL          ] OpenGL vendor <NVIDIA Corporation>
[INFO              ] [GL          ] OpenGL renderer <GeForce GTX 950/PCIe/SSE2>
[INFO              ] [GL          ] OpenGL parsed version: 4, 5
[INFO              ] [GL          ] Shading version <4.50 NVIDIA>
[INFO              ] [GL          ] Texture max size <16384>
[INFO              ] [GL          ] Texture max units <32>
[INFO              ] [Window      ] auto add sdl2 input provider
[INFO              ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO              ] [AudioGstplayer] Using Gstreamer 1.8.2.0
[INFO              ] [Audio       ] Providers: audio_gstplayer, audio_sdl2 (audio_ffpyplayer ignored)
[INFO              ] [Shader      ] Read </storage/Downloads/kivent-f08388cbb1052c7baf0c92a6a860f680550cda5c/examples/assets/glsl/positionshader.glsl>
[INFO              ] [Shader      ] Read </storage/Downloads/kivent-f08388cbb1052c7baf0c92a6a860f680550cda5c/examples/assets/glsl/positionshader.glsl>
Yay
camera1
tile_map
position
map_layer0
map_layer0_animator
map_layer1
map_layer1_animator
map_layer2
map_layer2_animator
[INFO              ] [Shader      ] Read </storage/Downloads/kivent-f08388cbb1052c7baf0c92a6a860f680550cda5c/examples/assets/glsl/positionshader.glsl>
[ERROR             ] [GameSystem  ] System_id: position not attached retrying in 1 sec. If you see this error once or twice, we are probably just waiting on the KV file to load. If you see it a whole bunch something is probably wrong. Make sure all systems are setup properly.
[INFO              ] [Base        ] Start application main loop
[INFO              ] [KivEnt      ] Vertex Format: vertex_format_4f registered. Size per vertex is: 16. Format is [('pos', 2, 'float', 0, False), ('uvs', 2, 'float', 8, False)].
[INFO              ] [KivEnt      ] Vertex Format: vertex_format_2f4ub registered. Size per vertex is: 12. Format is [('pos', 2, 'float', 0, False), ('v_color', 4, 'ubyte', 8, True)].
[INFO              ] [KivEnt      ] Vertex Format: vertex_format_7f registered. Size per vertex is: 28. Format is [('pos', 2, 'float', 0, False), ('uvs', 2, 'float', 8, False), ('rot', 1, 'float', 16, False), ('center', 2, 'float', 20, False)].
[INFO              ] [KivEnt      ] Vertex Format: vertex_format_7f4ub registered. Size per vertex is: 32. Format is [('pos', 2, 'float', 0, False), ('uvs', 2, 'float', 8, False), ('rot', 1, 'float', 16, False), ('center', 2, 'float', 20, False), ('v_color', 4, 'ubyte', 28, True)].
[INFO              ] [KivEnt      ] Vertex Format: vertex_format_4f4ub registered. Size per vertex is: 20. Format is [('pos', 2, 'float', 0, False), ('uvs', 2, 'float', 8, False), ('v_color', 4, 'ubyte', 16, True)].
[INFO              ] [KivEnt      ] Model Manager reserved space for vertex format: vertex_format_4f. 75 KiB was reserved for vertices, fitting a total of 4800. 25 KiB was reserved for indices fitting a total of 12800.
[INFO              ] [KivEnt      ] Model Manager reserved space for vertex format: vertex_format_2f4ub. 75 KiB was reserved for vertices, fitting a total of 6400. 25 KiB was reserved for indices fitting a total of 12800.
[INFO              ] [KivEnt      ] Model Manager reserved space for vertex format: vertex_format_7f. 75 KiB was reserved for vertices, fitting a total of 2742. 25 KiB was reserved for indices fitting a total of 12800.
[INFO              ] [KivEnt      ] Model Manager reserved space for vertex format: vertex_format_7f4ub. 75 KiB was reserved for vertices, fitting a total of 2400. 25 KiB was reserved for indices fitting a total of 12800.
[INFO              ] [KivEnt      ] Model Manager reserved space for vertex format: vertex_format_4f4ub. 75 KiB was reserved for vertices, fitting a total of 3840. 25 KiB was reserved for indices fitting a total of 12800.
[INFO              ] [KivEnt      ] map_layer1_animator allocated 4690 KiB
[INFO              ] [KivEnt      ] tile_map allocated 6262 KiB
[INFO              ] [KivEnt      ] position allocated 1176 KiB
[INFO              ] [KivEnt      ] map_layer0_animator allocated 4690 KiB
[INFO              ] [KivEnt      ] Batches for canvas: <kivy.graphics.instructions.RenderContext object at 0x7fb21c9ad710> will have 16384 verts and 131072 indices.VBO will be 256 in KiB per frame with 40 total vbos, an estimated 4096 enities fit in each batch with 4 verts per entity
[INFO              ] [KivEnt      ] map_layer2 allocated 26488 KiB
[INFO              ] [KivEnt      ] map_layer2_animator allocated 4690 KiB
[INFO              ] [KivEnt      ] Batches for canvas: <kivy.graphics.instructions.RenderContext object at 0x7fb21c9ad110> will have 16384 verts and 131072 indices.VBO will be 256 in KiB per frame with 40 total vbos, an estimated 4096 enities fit in each batch with 4 verts per entity
[INFO              ] [KivEnt      ] map_layer0 allocated 26488 KiB
[INFO              ] [KivEnt      ] Batches for canvas: <kivy.graphics.instructions.RenderContext object at 0x7fb21c9ad410> will have 16384 verts and 131072 indices.VBO will be 256 in KiB per frame with 40 total vbos, an estimated 4096 enities fit in each batch with 4 verts per entity
[INFO              ] [KivEnt      ] map_layer1 allocated 26488 KiB
[INFO              ] [KivEnt      ] We will need 106287 KiB for game, we have 204800 KiB
init game
Setting up tilemap
('loading', '/storage/Downloads/kivent-f08388cbb1052c7baf0c92a6a860f680550cda5c/examples/assets/maps/orthogonal.tmx')
[INFO              ] [GL          ] NPOT texture support is available
[INFO              ] [Base        ] Leaving application in progress...
 Traceback (most recent call last):
   File "/storage/Downloads/kivent-f08388cbb1052c7baf0c92a6a860f680550cda5c/examples/14_tmx_loader/main.py", line 69, in <module>
     YourAppNameApp().run()
   File "/usr/lib/python2.7/site-packages/kivy/app.py", line 828, in run
     runTouchApp()
   File "/usr/lib/python2.7/site-packages/kivy/base.py", line 487, in runTouchApp
     EventLoop.window.mainloop()
   File "/usr/lib/python2.7/site-packages/kivy/core/window/window_sdl2.py", line 621, in mainloop
     self._mainloop()
   File "/usr/lib/python2.7/site-packages/kivy/core/window/window_sdl2.py", line 364, in _mainloop
     EventLoop.idle()
   File "/usr/lib/python2.7/site-packages/kivy/base.py", line 327, in idle
     Clock.tick()
   File "/usr/lib/python2.7/site-packages/kivy/clock.py", line 512, in tick
     self._process_events()
   File "/usr/lib/python2.7/site-packages/kivy/clock.py", line 644, in _process_events
     event.tick(self._last_tick, remove)
   File "/usr/lib/python2.7/site-packages/kivy/clock.py", line 403, in tick
     ret = callback(self._dt)
   File "kivent_core/gameworld.pyx", line 281, in kivent_core.gameworld.GameWorld.init_gameworld.lambda (kivent_core/gameworld.c:6002)
   File "kivent_core/gameworld.pyx", line 278, in kivent_core.gameworld.GameWorld.init_gameworld (kivent_core/gameworld.c:6209)
   File "/storage/Downloads/kivent-f08388cbb1052c7baf0c92a6a860f680550cda5c/examples/14_tmx_loader/main.py", line 43, in init_game
     self.setup_tile_map()
   File "/storage/Downloads/kivent-f08388cbb1052c7baf0c92a6a860f680550cda5c/examples/14_tmx_loader/main.py", line 51, in setup_tile_map
     map_name = map_utils.parse_tmx(filename, self.gameworld)
   File "/usr/lib/python2.7/site-packages/kivent_maps/map_utils.py", line 115, in parse_tmx
     tiles, len(tilemap.layers))
   File "kivent_maps/map_manager.pyx", line 32, in kivent_maps.map_manager.MapManager.load_map (kivent_maps/map_manager.c:1807)
 TypeError: Argument 'name' has incorrect type (expected str, got unicode)
```

I added the "loading" print so I could verify it was getting the right path, and earlier I confirmed that name is a string, going in at least.

I noticed you seem to test with python 3.5, maybe this is a 2.7 related issue?  Or what am I doing wrong?  

Thanks for all your work!

**Comment by udiboy1209** [comment]
@spinningD20 This is certainly a python 2.7 issue, with string encoding.

```
TypeError: Argument 'name' has incorrect type (expected str, got unicode)
```

I am adding one more feature after which I'll look into code cleanup and python2 compatibility.

**Comment by spinningD20** [comment]
No problem, I'll test with 3.5.  I've only been sticking with 2.7 for Kivy based things because of the deployment processes are generally less problematic (for now).

**Comment by spinningD20** [comment]
```
/usr/bin/python3.5 /storage/Downloads/kivent-f08388cbb1052c7baf0c92a6a860f680550cda5c/examples/14_tmx_loader/main.py
[INFO              ] [Kivy        ] v1.9.1-dev
[INFO              ] [Python      ] v3.5.1 (default, Mar  3 2016, 09:29:07) 
[GCC 5.3.0]
[INFO              ] [Factory     ] 179 symbols loaded
[INFO              ] [Image       ] Providers: img_tex, img_dds, img_gif, img_sdl2 (img_pil, img_ffpyplayer ignored)
[INFO              ] [OSC         ] using <multiprocessing> for socket
[INFO              ] [Window      ] Provider: sdl2(['window_egl_rpi'] ignored)
[INFO              ] [GL          ] OpenGL version <b'4.5.0 NVIDIA 367.27'>
[INFO              ] [GL          ] OpenGL vendor <b'NVIDIA Corporation'>
[INFO              ] [GL          ] OpenGL renderer <b'GeForce GTX 950/PCIe/SSE2'>
[INFO              ] [GL          ] OpenGL parsed version: 4, 5
[INFO              ] [GL          ] Shading version <b'4.50 NVIDIA'>
[INFO              ] [GL          ] Texture max size <16384>
[INFO              ] [GL          ] Texture max units <32>
[INFO              ] [Window      ] auto add sdl2 input provider
[INFO              ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO              ] [AudioGstplayer] Using Gstreamer 1.8.2.0
[INFO              ] [Audio       ] Providers: audio_gstplayer, audio_sdl2 (audio_ffpyplayer ignored)
Yay
camera1
tile_map
position
map_layer0
map_layer0_animator
map_layer1
map_layer1_animator
map_layer2
map_layer2_animator
[INFO              ] [Shader      ] Read </storage/Downloads/kivent-f08388cbb1052c7baf0c92a6a860f680550cda5c/examples/assets/glsl/positionshader.glsl>
[INFO              ] [Shader      ] Read </storage/Downloads/kivent-f08388cbb1052c7baf0c92a6a860f680550cda5c/examples/assets/glsl/positionshader.glsl>
[INFO              ] [Shader      ] Read </storage/Downloads/kivent-f08388cbb1052c7baf0c92a6a860f680550cda5c/examples/assets/glsl/positionshader.glsl>
[ERROR             ] [GameSystem  ] System_id: position not attached retrying in 1 sec. If you see this error once or twice, we are probably just waiting on the KV file to load. If you see it a whole bunch something is probably wrong. Make sure all systems are setup properly.
[INFO              ] [ProbeSysfs  ] device match: /dev/input/event3
[INFO              ] [MTD         ] Read event from </dev/input/event3>
[INFO              ] [Base        ] Start application main loop
 Exception in thread Thread-1:
 Traceback (most recent call last):
   File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
     self.run()
   File "/usr/lib/python3.5/threading.py", line 862, in run
     self._target(*self._args, **self._kwargs)
   File "/usr/lib/python3.5/site-packages/kivy/input/providers/mtdev.py", line 219, in _thread_run
     _device = Device(_fn)
   File "/usr/lib/python3.5/site-packages/kivy/lib/mtdev.py", line 131, in __init__
     self._fd = os.open(filename, os.O_NONBLOCK | os.O_RDONLY)
 PermissionError: [Errno 13] Permission denied: '/dev/input/event3'
 
[INFO              ] [KivEnt      ] Vertex Format: vertex_format_7f4ub registered. Size per vertex is: 32. Format is [(b'pos', 2, b'float', 0, False), (b'uvs', 2, b'float', 8, False), (b'rot', 1, b'float', 16, False), (b'center', 2, b'float', 20, False), (b'v_color', 4, b'ubyte', 28, True)].
[INFO              ] [KivEnt      ] Vertex Format: vertex_format_2f4ub registered. Size per vertex is: 12. Format is [(b'pos', 2, b'float', 0, False), (b'v_color', 4, b'ubyte', 8, True)].
[INFO              ] [KivEnt      ] Vertex Format: vertex_format_7f registered. Size per vertex is: 28. Format is [(b'pos', 2, b'float', 0, False), (b'uvs', 2, b'float', 8, False), (b'rot', 1, b'float', 16, False), (b'center', 2, b'float', 20, False)].
[INFO              ] [KivEnt      ] Vertex Format: vertex_format_4f registered. Size per vertex is: 16. Format is [(b'pos', 2, b'float', 0, False), (b'uvs', 2, b'float', 8, False)].
[INFO              ] [KivEnt      ] Vertex Format: vertex_format_4f4ub registered. Size per vertex is: 20. Format is [(b'pos', 2, b'float', 0, False), (b'uvs', 2, b'float', 8, False), (b'v_color', 4, b'ubyte', 16, True)].
[INFO              ] [KivEnt      ] Model Manager reserved space for vertex format: vertex_format_7f4ub. 75 KiB was reserved for vertices, fitting a total of 2400. 25 KiB was reserved for indices fitting a total of 12800.
[INFO              ] [KivEnt      ] Model Manager reserved space for vertex format: vertex_format_2f4ub. 75 KiB was reserved for vertices, fitting a total of 6400. 25 KiB was reserved for indices fitting a total of 12800.
[INFO              ] [KivEnt      ] Model Manager reserved space for vertex format: vertex_format_7f. 75 KiB was reserved for vertices, fitting a total of 2742. 25 KiB was reserved for indices fitting a total of 12800.
[INFO              ] [KivEnt      ] Model Manager reserved space for vertex format: vertex_format_4f. 75 KiB was reserved for vertices, fitting a total of 4800. 25 KiB was reserved for indices fitting a total of 12800.
[INFO              ] [KivEnt      ] Model Manager reserved space for vertex format: vertex_format_4f4ub. 75 KiB was reserved for vertices, fitting a total of 3840. 25 KiB was reserved for indices fitting a total of 12800.
[INFO              ] [KivEnt      ] Batches for canvas: <kivy.graphics.instructions.RenderContext object at 0x7f99e2b17830> will have 16384 verts and 131072 indices.VBO will be 256 in KiB per frame with 40 total vbos, an estimated 4096 enities fit in each batch with 4 verts per entity
[INFO              ] [KivEnt      ] map_layer2 allocated 26488 KiB
[INFO              ] [KivEnt      ] tile_map allocated 6262 KiB
[INFO              ] [KivEnt      ] map_layer2_animator allocated 4690 KiB
[INFO              ] [KivEnt      ] Batches for canvas: <kivy.graphics.instructions.RenderContext object at 0x7f99e2b17498> will have 16384 verts and 131072 indices.VBO will be 256 in KiB per frame with 40 total vbos, an estimated 4096 enities fit in each batch with 4 verts per entity
[INFO              ] [KivEnt      ] map_layer1 allocated 26488 KiB
[INFO              ] [KivEnt      ] Batches for canvas: <kivy.graphics.instructions.RenderContext object at 0x7f99e2b17100> will have 16384 verts and 131072 indices.VBO will be 256 in KiB per frame with 40 total vbos, an estimated 4096 enities fit in each batch with 4 verts per entity
[INFO              ] [KivEnt      ] map_layer0 allocated 26488 KiB
[INFO              ] [KivEnt      ] map_layer1_animator allocated 4690 KiB
[INFO              ] [KivEnt      ] position allocated 1176 KiB
[INFO              ] [KivEnt      ] map_layer0_animator allocated 4690 KiB
[INFO              ] [KivEnt      ] We will need 106287 KiB for game, we have 204800 KiB
init game
Setting up tilemap
loading /storage/Downloads/kivent-f08388cbb1052c7baf0c92a6a860f680550cda5c/examples/assets/maps/orthogonal.tmx
[INFO              ] [GL          ] NPOT texture support is available
[INFO              ] [Base        ] Leaving application in progress...
 Traceback (most recent call last):
   File "/storage/Downloads/kivent-f08388cbb1052c7baf0c92a6a860f680550cda5c/examples/14_tmx_loader/main.py", line 69, in <module>
     YourAppNameApp().run()
   File "/usr/lib/python3.5/site-packages/kivy/app.py", line 828, in run
     runTouchApp()
   File "/usr/lib/python3.5/site-packages/kivy/base.py", line 487, in runTouchApp
     EventLoop.window.mainloop()
   File "/usr/lib/python3.5/site-packages/kivy/core/window/window_sdl2.py", line 613, in mainloop
     self._mainloop()
   File "/usr/lib/python3.5/site-packages/kivy/core/window/window_sdl2.py", line 362, in _mainloop
     EventLoop.idle()
   File "/usr/lib/python3.5/site-packages/kivy/base.py", line 327, in idle
     Clock.tick()
   File "/usr/lib/python3.5/site-packages/kivy/clock.py", line 515, in tick
     self._process_events()
   File "/usr/lib/python3.5/site-packages/kivy/clock.py", line 647, in _process_events
     event.tick(self._last_tick, remove)
   File "/usr/lib/python3.5/site-packages/kivy/clock.py", line 406, in tick
     ret = callback(self._dt)
   File "kivent_core/gameworld.pyx", line 281, in kivent_core.gameworld.GameWorld.init_gameworld.lambda (kivent_core/gameworld.c:6002)
   File "kivent_core/gameworld.pyx", line 278, in kivent_core.gameworld.GameWorld.init_gameworld (kivent_core/gameworld.c:6209)
   File "/storage/Downloads/kivent-f08388cbb1052c7baf0c92a6a860f680550cda5c/examples/14_tmx_loader/main.py", line 43, in init_game
     self.setup_tile_map()
   File "/storage/Downloads/kivent-f08388cbb1052c7baf0c92a6a860f680550cda5c/examples/14_tmx_loader/main.py", line 51, in setup_tile_map
     map_name = map_utils.parse_tmx(filename, self.gameworld)
   File "/usr/lib/python3.5/site-packages/kivent_maps/map_utils.py", line 125, in parse_tmx
     loaded_map.hex_side_length = tilemap.hexsidelength
   File "kivent_maps/map_data.pyx", line 217, in kivent_maps.map_data.TileMap.hex_side_length.__set__ (kivent_maps/map_data.c:5139)
 TypeError: an integer is required
```

**Comment by udiboy1209** [comment]
@spinningD20 the last commit should fix your error. You should also update to python-tmx-1.8.1, the previous version had some error.

**Comment by spinningD20** [comment]
updating just the kivent maps module got the example to run, as you said.  Nice work!  I'll plunge deeper into the example to get a better understanding of how to transition over from what I'm using currently.  Thanks.

**Comment by udiboy1209** [comment]
@spinningD20 thanks for all the feedback :grin: ! Those seams look like a rounding off issue maybe, I'll look into it when I'm cleaning up this entire module.

**Pull request merged**
