### PR TITLE
Texture flipping

### PR DESCRIPTION
**Pull request by rocktavious**
This allows one to flip or rotate the UV's of a textured rectangle.  This is needed because tilemaps from the program Tiled, allow this functionality.

### CODE REVIEW

**Comment by Kovak** [comment]
What is with the min/max thing going on with some coordinates? It doesn't seem like it should be necessary but, I am not certain what your intention with it is.

**Comment by rocktavious** [comment]
So initially i implemented without this, using that standard uv transformation i thought i would need to do, but then when i tested it out, i found a problem when a model was both rotated and then flipped.  So to support this i had to rework the way flipping works such that if the texture is rotated 90 degrees your still flipping the texture horizontally and not resetting it back to proper orientation, and then flipping horizontally, effectively loosing your 90 degree rotation.

**Comment by Kovak** [comment]
It seems to me that this might not introduce the expected behavior. Since the algorithm is operating on the current coordinates, it should not be necessary for this min/max determination as that is actually making it so occasionally it does something completely different from the expected.
Let's work through multiple calls of these functions, keeping coordinates as they are in the initial function:

Initial rect:
(u2, v2)  (u3, v3)

(u1, v1)   (u4, v4)

Now we rotate it 90 degrees clockwise.
(u1, v1)  (u2, v2)

(u4, v4)   (u3, v3)

Now we flip it horizontally, the expected result will be:

(u2, v1)  (u1, v2)

(u3, v4)  (u4, v3)

but with your algorithm: u4, and u3 will be == uMax, and u1, u2 will == uMin in a textured sprite as the coordinates are the same value. So first of all we are actually compressing the 4 coordinates into 2, this would definitely limit the algorithm to no longer working in the case of a trapezoid instead of a square/rect, even though the algorithm should be the same.

so we get:
(u3, v1) (u4, v2)

(u2, v4)  (u1, v3)

This is more than just a simple horizontal flip and not the expected result for this function. It seems maybe you have confused proper order of invocation for subsequent calls and the actual implementation of the individual calls.

**Comment by Kovak** [comment]
This has been replaced by #222

**Pull request closed without merging**
