### PR TITLE
memory leak fix

### PR DESCRIPTION
**Pull request by mahomahomaho**
Related to #179 - it's very strange, and I have no idea why such bizzare change fixes things, but apparently works, tested few times on PC and on android.

### CODE REVIEW

**Comment by Kovak** [comment]
This definitely is not the appropriate fix for the problem. This will just cause a different type of leak under other conditions. clear_frames does need to get called, but perhaps there is some additional cleanup that needs to be part of it.

**Comment by mahomahomaho** [comment]
yeah, it doesn't sound like it's proper solution. But is for me! :) If it's leak, then it's way smaller than was before ...

**Comment by mahomahomaho** [comment]
ok, I just found side effect of this "fix" - flickering when change size of entity/replaced with entity with different size. However, this "fix" really stopped leaking and stopped killing android app.

**Comment by Kovak** [comment]
I believe this was just properly fixed by #247

**Comment by mahomahomaho** [comment]
yeah, I just checked and it's fixed in #247

**Pull request closed without merging**
