### PR TITLE
Fixed python 2.7+ and python 3 support

### PR DESCRIPTION
**Pull request by dummerbd**

### CODE REVIEW

**Comment by Kovak** [comment]
Thanks very much for this. I am not super familiar with this particular area of things, can you post a small description of what the bug being fixed is here for the record?

**Comment by udiboy1209** [comment]
Looks like a fix for building Kivent on OSX using both py2 and py3. @Kovak, do you have access to OSX to test this? 

Also, I think build checks for such PRs could be automated with a CI like Travis.

**Comment by Kovak** [comment]
I guess this is where my interest comes in, the solution that did not use this new "check_output" but instead used get_output worked on OSX for me, I'd be curious to hear about the condition that this fixes.

**Comment by dummerbd** [comment]
Originally I made a similar fix on `master` but the code here already has the fixes except for using the now deprecated (as of Python 2.7) `commands` module. The `subprocess` module should be used instead. There is a `checkoutput` in the `subprocess` module but it's not available in older Python versions.

I've just started looking at kivy and kivent this week. I think its a really awesome project and would love to help out a bit. I think setting up Travis CI with multiple python setups would be useful. Also, I found it a little tricky to get everything setup in a local venv on OS X and Ubuntu. I wouldn't mind helping out with documentation a bit.

**Comment by Kovak** [comment]
Exactly the type of explanation I was looking for. Do you think you would mind making sure the fix is in place for the other modules setup.py as well. I would be happy for any help on the Travis CI, documentation, and OSX/Ubuntu niceties. Not really an area of expertise for me so we definitely lag here.

**Comment by dummerbd** [comment]
I'm actually running into issues with the kivent_cymunk module on Ubuntu 16.06. I'll take a look at it later tonight.

```bash
cymunk git:(2.2-dev) ➜ python setup.py build_ext --inplace
Traceback (most recent call last):
  File "setup.py", line 95, in <module>
    cymunk_dirname = pkgutil.get_loader("cymunk").filename
AttributeError: 'SourceFileLoader' object has no attribute 'filename'

```

**Comment by Kovak** [comment]
Make sure you have the cymunk module installed separately.

**Comment by dummerbd** [comment]
Yeah I have `cymunk` installed through pip in the venv. I was able to install all the modules and test them with the tutorials for the master branch on both OS X and Ubuntu. So, this must be an issue on this branch. I'll try it on my Mac later tonight too.

**Comment by dummerbd** [comment]
I added some fixes for the cymunk and particles modules for OS X and probably Ubuntu (I didn't check but it should be).

**Comment by Kovak** [comment]
Looking good! One final thing, don't we need to have the importerror check_output definition for everywhere?

**Comment by Kovak** [comment]
Thanks!

**Comment by dummerbd** [comment]
I think we can exclude 2.6 support and just aim for current versions of python: 2.7 and 3.4+

I'm looking into setting up TravisCI with tox/pyenv with my fork so we can automate compatibility tests

**Pull request merged**
