### PR TITLE
Add version number to packages and setup files (2.2 dev)

### LINKED ISSUE #104: modules version missing
If kivent modules are installed rather that built in place, pip reports invalid version number. Do we want to change it? the 0.0.0 version is pretty misleading.

### PR DESCRIPTION
**Pull request by labuzm**
fixes #104 

I didn't change the version number in docs/source/conf.py due to #106.

### CODE REVIEW

**Comment by Kovak** [comment]
beautiful! I'll need to set aside some time to look through everything but a quick glance says it looks great. It will be merged before 2.2 :)

**Comment by labuzm** [comment]
Great! :)

**Comment by labuzm** [comment]
updated

**Comment by Kovak** [comment]
thanks :)

**Comment by labuzm** [comment]
:+1:

**Pull request merged**
