### PR TITLE
Add map module boilerplate

### PR DESCRIPTION
**Pull request by udiboy1209**
Added data holding classes and a map manager. Will add a system soon

### CODE REVIEW

**Comment by udiboy1209** [comment]
@kovak texkeys stored in tile_texture turn out to be random but I cant figure out why. Here's the error log http://paste.ubuntu.com/17103944/ when testing example 13. Can you see where the error could be?

**Comment by Kovak** [comment]
I think this is because in MapManager.load_texture you load the data into MapManager.textures_block,
but in map_utils.init_entities_from_map you attempt to use map_data.TileMap.get_tile to get the texture data. Unless there is a step I'm missing this is an allocated but unfilled memory block.

**Comment by Kovak** [comment]
@udiboy1209 I have made a branch specifically for your gsoc work as we discussed earlier:
https://github.com/kivy/kivent/tree/tiled_gsoc_2016

I think going forward we should make our PR into this branch as features are completed so that we can break up the code review into smaller units.

**Comment by udiboy1209** [comment]
continuing in #141

**Pull request closed without merging**
